# This workflow will build a python script, generate an executable and upload it.

name: Build python script

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
          if [ -f requirements.txt ]; then pip install -r requirements/default.txt; fi
          pip install pyinstaller
      - name: Build script
        run: |
          bash /scripts/build-installer.sh ${{matrix.os}}-install-checkpoint
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }} Installer
          path: dist/${{ matrix.os }}-install-checkpoint
